name: checks
on: [push, pull_request]
jobs:
  core:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install -e ".[test,remote]"
      - run: python -m pytest -q
      - run: ruff check src tests
